version: "3"
networks:
  test-network:
    external: true

services:
  postgres:
    image: postgres:latest
    container_name: test_postgres
    ports:
      - 54321:5432
    networks:
      - test-network

  nginx:
    image: nginx:latest
    container_name: test_nginx
    volumes:
      - "./app:/var/www/symfony:rw"
      - "./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 80:80
    networks:
      - test-network

  app:
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    container_name: test_app
    env_file:
      - .env
    volumes:
      - "./app:/var/www/symfony:rw"
    networks:
      - test-network